BEGIN;

-- Existing users and issues are intentionally preserved. Their current schema is
-- compatible with the integer foreign keys used by the tables below.

ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id VARCHAR(255) UNIQUE;
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
-- Adding a google ID column for "Sign in with Google"

ALTER TABLE issues
    ADD COLUMN IF NOT EXISTS latitude numeric(9, 6),
    ADD COLUMN IF NOT EXISTS longitude numeric(9, 6);

CREATE TABLE IF NOT EXISTS issue_images (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id integer NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    uploaded_by integer REFERENCES users(id) ON DELETE SET NULL,
    image_url text NOT NULL,
    caption text,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS issue_verifications (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id integer NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    user_id integer REFERENCES users(id) ON DELETE SET NULL,
    verification_status varchar(30) NOT NULL DEFAULT 'pending',
    comment text,
    verified_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (issue_id, user_id)
);

CREATE TABLE IF NOT EXISTS ai_analysis (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id integer NOT NULL UNIQUE REFERENCES issues(id) ON DELETE CASCADE,
    summary text,
    recommended_priority varchar(30),
    estimated_budget numeric(12, 2),
    estimated_volunteers integer,
    confidence_score numeric(5, 4),
    raw_result jsonb,
    analyzed_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS action_plans (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id integer NOT NULL UNIQUE REFERENCES issues(id) ON DELETE CASCADE,
    created_by integer REFERENCES users(id) ON DELETE SET NULL,
    title varchar(255) NOT NULL,
    description text,
    status varchar(30) NOT NULL DEFAULT 'draft',
    planned_start_date date,
    planned_end_date date,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS action_plan_steps (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_plan_id integer NOT NULL REFERENCES action_plans(id) ON DELETE CASCADE,
    step_order integer NOT NULL,
    title varchar(255) NOT NULL,
    description text,
    status varchar(30) NOT NULL DEFAULT 'pending',
    estimated_days integer,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (action_plan_id, step_order)
);

CREATE TABLE IF NOT EXISTS volunteer_recommendations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id integer NOT NULL REFERENCES issues(id) ON DELETE RESTRICT,
    action_plan_id integer REFERENCES action_plans(id) ON DELETE SET NULL,
    volunteer_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    recommended_role varchar(100),
    recommendation_score numeric(5, 4),
    reason text,
    status varchar(30) NOT NULL DEFAULT 'recommended',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (issue_id, volunteer_id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users(id) ON DELETE SET NULL,
    notification_type varchar(50) NOT NULL,
    title varchar(255) NOT NULL,
    message text NOT NULL,
    issue_id integer REFERENCES issues(id) ON DELETE SET NULL,
    event_id integer,
    task_id integer,
    is_read boolean NOT NULL DEFAULT false,
    read_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS volunteer_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id integer REFERENCES users(id) ON DELETE SET NULL,
    issue_id integer REFERENCES issues(id) ON DELETE SET NULL,
    title varchar(255) NOT NULL,
    description text,
    location_name varchar(255),
    division varchar(100),
    district varchar(100),
    upazila varchar(100),
    union_name varchar(100),
    village varchar(100),
    starts_at timestamp without time zone NOT NULL,
    ends_at timestamp without time zone,
    volunteer_capacity integer,
    status varchar(30) NOT NULL DEFAULT 'planned',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS event_participation (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id integer NOT NULL REFERENCES volunteer_events(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    participation_status varchar(30) NOT NULL DEFAULT 'registered',
    joined_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone,
    UNIQUE (event_id, user_id)
);

CREATE TABLE IF NOT EXISTS tasks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_plan_id integer REFERENCES action_plans(id) ON DELETE SET NULL,
    event_id integer REFERENCES volunteer_events(id) ON DELETE SET NULL,
    assigned_to integer REFERENCES users(id) ON DELETE SET NULL,
    title varchar(255) NOT NULL,
    description text,
    status varchar(30) NOT NULL DEFAULT 'pending',
    priority varchar(30) NOT NULL DEFAULT 'medium',
    due_at timestamp without time zone,
    completed_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS resources (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_plan_id integer REFERENCES action_plans(id) ON DELETE SET NULL,
    event_id integer REFERENCES volunteer_events(id) ON DELETE SET NULL,
    provided_by integer REFERENCES users(id) ON DELETE SET NULL,
    name varchar(255) NOT NULL,
    resource_type varchar(100),
    quantity numeric(12, 2),
    unit varchar(50),
    estimated_cost numeric(12, 2),
    status varchar(30) NOT NULL DEFAULT 'needed',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS progress_updates (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id integer NOT NULL REFERENCES issues(id) ON DELETE RESTRICT,
    action_plan_id integer REFERENCES action_plans(id) ON DELETE SET NULL,
    task_id integer REFERENCES tasks(id) ON DELETE SET NULL,
    updated_by integer REFERENCES users(id) ON DELETE SET NULL,
    title varchar(255),
    update_text text NOT NULL,
    progress_percent numeric(5, 2),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_issue_images_issue_id ON issue_images(issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_images_uploaded_by ON issue_images(uploaded_by);
CREATE INDEX IF NOT EXISTS idx_issue_verifications_issue_id ON issue_verifications(issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_verifications_user_id ON issue_verifications(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_analysis_issue_id ON ai_analysis(issue_id);
CREATE INDEX IF NOT EXISTS idx_action_plans_issue_id ON action_plans(issue_id);
CREATE INDEX IF NOT EXISTS idx_action_plan_steps_plan_id ON action_plan_steps(action_plan_id);
CREATE INDEX IF NOT EXISTS idx_volunteer_recommendations_issue_id ON volunteer_recommendations(issue_id);
CREATE INDEX IF NOT EXISTS idx_volunteer_recommendations_volunteer_id ON volunteer_recommendations(volunteer_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_issue_id ON notifications(issue_id);
CREATE INDEX IF NOT EXISTS idx_volunteer_events_organizer_id ON volunteer_events(organizer_id);
CREATE INDEX IF NOT EXISTS idx_volunteer_events_issue_id ON volunteer_events(issue_id);
CREATE INDEX IF NOT EXISTS idx_event_participation_event_id ON event_participation(event_id);
CREATE INDEX IF NOT EXISTS idx_event_participation_user_id ON event_participation(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_action_plan_id ON tasks(action_plan_id);
CREATE INDEX IF NOT EXISTS idx_tasks_event_id ON tasks(event_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_resources_action_plan_id ON resources(action_plan_id);
CREATE INDEX IF NOT EXISTS idx_resources_event_id ON resources(event_id);
CREATE INDEX IF NOT EXISTS idx_progress_updates_issue_id ON progress_updates(issue_id);
CREATE INDEX IF NOT EXISTS idx_progress_updates_action_plan_id ON progress_updates(action_plan_id);
CREATE INDEX IF NOT EXISTS idx_progress_updates_task_id ON progress_updates(task_id);

-- These cross-references are added after both tables exist.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'notifications_event_id_fkey'
    ) THEN
        ALTER TABLE notifications
            ADD CONSTRAINT notifications_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES volunteer_events(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'notifications_task_id_fkey'
    ) THEN
        ALTER TABLE notifications
            ADD CONSTRAINT notifications_task_id_fkey
            FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_notifications_event_id ON notifications(event_id);
CREATE INDEX IF NOT EXISTS idx_notifications_task_id ON notifications(task_id);

COMMIT;
